# Generated by Django 2.2.6 on 2019-10-30 20:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "application_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("submit_date", models.DateField(default=datetime.datetime.now)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "ACTIVE"), ("INACTIVE", "INACTIVE")],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
            ],
        )
    ]
