# Generated by Django 2.2.6 on 2019-10-27 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='email',
            new_name='candidate',
        ),
    ]
