# Generated by Django 2.2.6 on 2019-11-01 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("apply", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="application",
            name="first_name",
            field=models.CharField(default="alex", max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="application",
            name="gender",
            field=models.CharField(
                choices=[("F", "Female"), ("M", "Male"), ("X", "Non Binary")],
                default="X",
                max_length=1,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="application",
            name="last_name",
            field=models.CharField(default="Smith", max_length=30),
            preserve_default=False,
        ),
    ]
