# Generated by Django 2.2.6 on 2019-11-11 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("uplyft", "0002_activeprofile"),
        ("jobs", "0001_initial"),
        ("apply", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="candidate",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="uplyft.Candidate",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="application",
            name="candidate_profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="uplyft.CandidateProfile",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="job",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="jobs.Job"
            ),
            preserve_default=False,
        ),
    ]
