# Generated by Django 2.2.6 on 2019-11-02 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("apply", "0001_initial"),
        ("jobs", "0001_initial"),
        ("uplyft", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="candidate",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="uplyft.Candidate",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="candidate_profile",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="uplyft.CandidateProfile",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="job",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="jobs.Job"
            ),
        ),
    ]
