# Generated by Django 2.2.6 on 2019-10-30 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0002_auto_20191030_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='application_id',
        ),
        migrations.AddField(
            model_name='application',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
