# Generated by Django 2.2.6 on 2019-12-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("apply", "0002_auto_20191118_1623")]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="submit_date",
            field=models.DateField(auto_now_add=True),
        )
    ]
