# Generated by Django 2.2.6 on 2019-11-01 08:27

from django.db import migrations, models
import localflavor.us.models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [("apply", "0002_auto_20191101_0337")]

    operations = [
        migrations.AddField(
            model_name="application",
            name="additional_info",
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name="application",
            name="address_line",
            field=models.CharField(default="Main Street", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="application",
            name="cover_letter",
            field=models.TextField(default="To whom it may concern", max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="application",
            name="education",
            field=models.TextField(default="NYU", max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="application",
            name="email",
            field=models.EmailField(default="mail@example.com", max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="application",
            name="experiences",
            field=models.TextField(default="2019-Present", max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="application",
            name="phone",
            field=phone_field.models.PhoneField(
                default="2123435678", help_text="Contact phone number", max_length=31
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="application",
            name="porfolio",
            field=models.URLField(
                default="myporfolio.com", help_text="Maximum 200 characters"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="application",
            name="state",
            field=localflavor.us.models.USStateField(default="NY", max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="application",
            name="zip_code",
            field=localflavor.us.models.USZipCodeField(default=11201, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[("AP", "Applied"), ("AC", "Accepted"), ("RE", "Rejected")],
                default="AP",
                max_length=2,
            ),
        ),
    ]
