# Generated by Django 2.2.8 on 2019-12-10 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apply", "0003_auto_20191209_1455"),
        ("apply", "0003_auto_20191207_1520"),
    ]

    operations = []
