# Generated by Django 2.2.6 on 2019-11-01 08:44

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [("apply", "0004_auto_20191101_0427")]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="phone",
            field=phone_field.models.PhoneField(max_length=31),
        )
    ]
