# Generated by Django 2.2.6 on 2019-11-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("apply", "0005_auto_20191101_0444")]

    operations = [
        migrations.AddField(
            model_name="application",
            name="ethnicity",
            field=models.CharField(
                choices=[
                    ("HL", "Hispanic or Latino"),
                    ("OT", "Not Hispanic or Latino"),
                    (None, "Prefer not to specify"),
                ],
                default=None,
                max_length=2,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="application",
            name="health_conditions",
            field=models.CharField(
                choices=[
                    ("POSITIVE", "One or more health conditions"),
                    ("NEGATIVE", "None listed apply"),
                    (None, "Prefer not to specify"),
                ],
                default=None,
                max_length=8,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="application",
            name="race",
            field=models.CharField(
                choices=[
                    ("NATIVE", "American indian or Alaska Native"),
                    ("ASIAN", "Asian"),
                    ("BLACK", "Black or African American"),
                    ("PACIFIC", "Native Hawaiian or Pacific Islander"),
                    ("WHITE", "White"),
                    (None, "Prefer not to specify"),
                ],
                default=None,
                max_length=7,
            ),
            preserve_default=False,
        ),
    ]
