# Generated by Django 2.2.6 on 2019-11-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("apply", "0006_auto_20191101_1132")]

    operations = [
        migrations.AddField(
            model_name="application",
            name="veteran",
            field=models.CharField(
                choices=[
                    ("POSITIVE", "Veteran"),
                    ("NEGATIVE", "Not veteran"),
                    (None, "Prefer not to specify"),
                ],
                default=None,
                max_length=8,
            ),
            preserve_default=False,
        )
    ]
