# Generated by Django 2.2.6 on 2019-11-01 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("apply", "0007_application_veteran")]

    operations = [
        migrations.RenameField(
            model_name="application",
            old_name="porfolio_website",
            new_name="portfolio_website",
        )
    ]
