# Generated by Django 2.2.6 on 2019-11-01 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("uplyft", "0002_candidateprofile"),
        ("apply", "0008_auto_20191101_1700"),
    ]

    operations = [
        migrations.RemoveField(model_name="application", name="additional_info"),
        migrations.RemoveField(model_name="application", name="address_line"),
        migrations.RemoveField(model_name="application", name="cover_letter"),
        migrations.RemoveField(model_name="application", name="education"),
        migrations.RemoveField(model_name="application", name="email"),
        migrations.RemoveField(model_name="application", name="ethnicity"),
        migrations.RemoveField(model_name="application", name="experiences"),
        migrations.RemoveField(model_name="application", name="first_name"),
        migrations.RemoveField(model_name="application", name="gender"),
        migrations.RemoveField(model_name="application", name="health_conditions"),
        migrations.RemoveField(model_name="application", name="last_name"),
        migrations.RemoveField(model_name="application", name="phone"),
        migrations.RemoveField(model_name="application", name="portfolio_website"),
        migrations.RemoveField(model_name="application", name="race"),
        migrations.RemoveField(model_name="application", name="state"),
        migrations.RemoveField(model_name="application", name="veteran"),
        migrations.RemoveField(model_name="application", name="zip_code"),
        migrations.AddField(
            model_name="application",
            name="candidate_profile",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="uplyft.CandidateProfile",
            ),
            preserve_default=False,
        ),
    ]
