# Generated by Django 2.2.6 on 2019-11-02 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("apply", "0009_auto_20191101_1753")]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="candidate_profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="uplyft.CandidateProfile",
            ),
        )
    ]
