# Generated by Django 2.2.6 on 2019-11-10 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("applications", "0001_initial")]

    operations = [migrations.DeleteModel(name="ActiveApplication")]
