# Generated by Django 2.2.6 on 2019-10-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='id',
        ),
        migrations.AlterField(
            model_name='job',
            name='job_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
