# Generated by Django 2.2.6 on 2019-11-06 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("jobs", "0002_savedjobs")]

    operations = [
        migrations.RenameField(
            model_name="savedjobs", old_name="job_id", new_name="job"
        )
    ]
