# Generated by Django 2.2.6 on 2019-11-06 16:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("jobs", "0003_auto_20191106_0513"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="savedjobs", unique_together={("job", "user")}
        )
    ]
