# Generated by Django 2.2.6 on 2019-11-26 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20191122_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentprofile',
            name='website',
            field=models.URLField(blank=True, help_text='e.g. http://example.com', null=True),
        ),
    ]
