language: python

python:
  - 3.7

install:
  - pip install -r requirements.txt

before_script:
  - python manage.py migrate
  - python manage.py collectstatic --noinput

script:
  - black --check .
  - flake8 .
  - coverage run --source=candidate_login,jobs,register,teamone,tests,uplyft,apply,dashboard manage.py test

after_script:
  - coveralls