language: python

python:
  - 3.7

addons:
  firefox: latest

before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.11.1-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver

install:
  - pip install -r requirements.txt

before_script:
  - python manage.py migrate
  - python manage.py collectstatic --noinput

script:
  - black --check .
  - flake8 .
  - coverage run --source=candidate_profile,candidate_login,employer_login,jobs,register,uplyft,apply,applications,dashboard manage.py test uplyft.tests.test_selenium_candidate_profile
  - cat geckodriver.log

after_script:
  - coveralls