# Generated by Django 2.2.6 on 2019-10-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateRegistrationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, help_text="The candidate's first name.", max_length=60)),
                ('last_name', models.CharField(blank=True, help_text="The candidate's last name.", max_length=60)),
                ('email', models.EmailField(blank=True, help_text="The candidate's email address.", max_length=200)),
                ('password', models.CharField(blank=True, help_text="The candidate's password.", max_length=200)),
                ('password_retype', models.CharField(blank=True, help_text="The candidate's password, again.", max_length=200)),
            ],
        ),
    ]
