# Generated by Django 2.2.6 on 2019-10-09 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uplyft', '0002_auto_20191009_1206'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CandidateRegistrationModel',
        ),
    ]
