# Generated by Django 2.2.6 on 2019-11-01 21:53

from django.db import migrations, models
import localflavor.us.models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [("uplyft", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="CandidateProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                (
                    "gender",
                    models.CharField(
                        choices=[("F", "Female"), ("M", "Male"), ("X", "Non Binary")],
                        max_length=1,
                    ),
                ),
                (
                    "ethnicity",
                    models.CharField(
                        choices=[
                            ("HL", "Hispanic or Latino"),
                            ("OT", "Not Hispanic or Latino"),
                            (None, "Prefer not to specify"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "race",
                    models.CharField(
                        choices=[
                            ("NATIVE", "American indian or Alaska Native"),
                            ("ASIAN", "Asian"),
                            ("BLACK", "Black or African American"),
                            ("PACIFIC", "Native Hawaiian or Pacific Islander"),
                            ("WHITE", "White"),
                            (None, "Prefer not to specify"),
                        ],
                        max_length=7,
                    ),
                ),
                (
                    "health_conditions",
                    models.CharField(
                        choices=[
                            ("POSITIVE", "One or more health conditions"),
                            ("NEGATIVE", "None listed apply"),
                            (None, "Prefer not to specify"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "veteran",
                    models.CharField(
                        choices=[
                            ("POSITIVE", "Veteran"),
                            ("NEGATIVE", "Not veteran"),
                            (None, "Prefer not to specify"),
                        ],
                        max_length=8,
                    ),
                ),
                ("address_line", models.CharField(max_length=100)),
                ("zip_code", localflavor.us.models.USZipCodeField(max_length=10)),
                ("state", localflavor.us.models.USStateField(max_length=2)),
                ("phone", phone_field.models.PhoneField(max_length=31)),
                ("email", models.EmailField(max_length=254)),
                (
                    "portfolio_website",
                    models.URLField(help_text="Maximum 200 characters"),
                ),
                ("cover_letter", models.TextField(max_length=10000)),
                ("experiences", models.TextField(max_length=10000)),
                ("education", models.TextField(max_length=10000)),
                ("additional_info", models.TextField(blank=True, max_length=10000)),
            ],
        )
    ]
