# Generated by Django 2.2.6 on 2019-11-13 16:05

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('uplyft', '0002_activeprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
