# Generated by Django 2.2.6 on 2019-11-02 01:21

from django.db import migrations, models
import localflavor.us.models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [("uplyft", "0002_candidateprofile")]

    operations = [
        migrations.AlterField(
            model_name="candidateprofile",
            name="additional_info",
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="candidateprofile",
            name="address_line",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="candidateprofile",
            name="cover_letter",
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="candidateprofile",
            name="education",
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="candidateprofile",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="candidateprofile",
            name="ethnicity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("HL", "Hispanic or Latino"),
                    ("OT", "Not Hispanic or Latino"),
                    (None, "Prefer not to specify"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="candidateprofile",
            name="experiences",
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="candidateprofile",
            name="first_name",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="candidateprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("F", "Female"), ("M", "Male"), ("X", "Non Binary")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="candidateprofile",
            name="health_conditions",
            field=models.CharField(
                blank=True,
                choices=[
                    ("POSITIVE", "One or more health conditions"),
                    ("NEGATIVE", "None listed apply"),
                    (None, "Prefer not to specify"),
                ],
                max_length=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="candidateprofile",
            name="last_name",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="candidateprofile",
            name="phone",
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True),
        ),
        migrations.AlterField(
            model_name="candidateprofile",
            name="portfolio_website",
            field=models.URLField(
                blank=True, help_text="Maximum 200 characters", null=True
            ),
        ),
        migrations.AlterField(
            model_name="candidateprofile",
            name="race",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NATIVE", "American indian or Alaska Native"),
                    ("ASIAN", "Asian"),
                    ("BLACK", "Black or African American"),
                    ("PACIFIC", "Native Hawaiian or Pacific Islander"),
                    ("WHITE", "White"),
                    (None, "Prefer not to specify"),
                ],
                max_length=7,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="candidateprofile",
            name="state",
            field=localflavor.us.models.USStateField(
                blank=True, max_length=2, null=True
            ),
        ),
        migrations.AlterField(
            model_name="candidateprofile",
            name="veteran",
            field=models.CharField(
                blank=True,
                choices=[
                    ("POSITIVE", "Veteran"),
                    ("NEGATIVE", "Not veteran"),
                    (None, "Prefer not to specify"),
                ],
                max_length=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="candidateprofile",
            name="zip_code",
            field=localflavor.us.models.USZipCodeField(
                blank=True, max_length=10, null=True
            ),
        ),
    ]
