# Generated by Django 2.2.6 on 2019-10-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uplyft', '0003_auto_20191010_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=200, unique=True, verbose_name='email address'),
        ),
    ]
