# Generated by Django 2.2.6 on 2019-10-30 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uplyft', '0007_merge_20191030_1353'),
        ('uplyft', '0004_auto_20191030_1519'),
    ]

    operations = [
    ]
