# Generated by Django 2.2.6 on 2019-12-04 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("uplyft", "0007_auto_20191204_0001"),
        ("uplyft", "0007_auto_20191129_1003"),
    ]

    operations = []
