# Generated by Django 2.2.6 on 2019-12-09 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_entity_type",
                    models.CharField(
                        choices=[
                            ("ARJ", "Application Rejected"),
                            ("ARV", "Application Reviewed"),
                        ],
                        max_length=3,
                    ),
                ),
                ("notification_entity_fk_pk", models.PositiveIntegerField()),
                (
                    "notification_status",
                    models.CharField(
                        choices=[
                            ("UNRD", "Unread"),
                            ("READ", "Read"),
                            ("ARCV", "Archived"),
                        ],
                        max_length=4,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        )
    ]
