# Generated by Django 2.2.6 on 2019-12-09 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("notifications", "0001_initial")]

    operations = [
        migrations.RenameField(
            model_name="notification",
            old_name="notification_entity_fk_pk",
            new_name="entity_fk_pk",
        ),
        migrations.RenameField(
            model_name="notification",
            old_name="notification_entity_type",
            new_name="entity_type",
        ),
        migrations.RenameField(
            model_name="notification", old_name="notification_status", new_name="status"
        ),
    ]
