# Generated by Django 2.2.6 on 2019-12-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("notifications", "0003_auto_20191209_1530")]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="status",
            field=models.CharField(
                choices=[("UNRD", "Unread"), ("READ", "Read"), ("ARCV", "Archived")],
                default="UNRD",
                max_length=4,
            ),
        )
    ]
